
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\20250103-animals-meio1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\tiger-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\20241227-animals-chris1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\bull-4.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\20250102-animals-rick1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\dog-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\20241227-animals-dana1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\sheep-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\20241231-animals-lydia1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\chicken-3.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\20241227-animals-max1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\pig-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\animals-title2.png" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\chinesezodiacplacemat1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\rat-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\chineseratcharacter1.gif" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\rat-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\bull-4.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\tiger-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\rabbit-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\dragon-2.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\snake-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\horse-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\sheep-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\monkey-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\chicken-3.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\dog-1.jpg" images
copy "z:\users\rshab\Documents\My Home\rshabsin\_uimages\pig-1.jpg" images